config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get "about" => "pages#about"
  get "contact-us" => "pages#contact_us"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Omrails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="text-white py-3 px-10 bg-cyan-400 bg-opacity-40 fixed w-full z-10">
      <%= link_to "Home", root_path, class: "text-white no-underline" %>
      <%= link_to "About", about_path, class: "text-white mx-3 no-underline" %>
      <%= link_to "Contact Us", contact_us_path, class: "text-white no-underline" %>
    </nav>
    <%= yield %>
    <footer class="mt-20">
      <hr class="border-slate-400 mx-10" />
      <p class="text-center text-xs text-slate-400">	&#169; 2023 Abisola <3</p>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<div>
    <figure class="w-full h-[55vh] relative">
        <img src=<%= image_path("rails_project_header.jpg") %> class="w-full h-full object-cover" />
        <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-1/2">
            <h2 class="font-bold text-white text-4xl">About</h2>
            <p class="text-slate-300">This is about page</p>
        </div> 
    </figure> 
</div>

app/views/pages/contact_us.html.erb
<div>
    <figure class="w-full h-[55vh] relative">
        <img src=<%= image_path("rails_project_header.jpg") %> class="w-full h-full object-cover" />
        <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-1/2">
            <h2 class="font-bold text-white text-4xl">Contact Us</h2>
            <p class="text-slate-300">This is contact page</p>
        </div>  
    </figure> 
</div>

app/views/pages/home.html.erb
<div>
    <figure class="w-full h-[55vh] relative">
        <img src=<%= image_path("rails_project_header.jpg") %> class="w-full h-full object-cover" />
        <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-1/2">
            <h2 class="font-bold text-white text-4xl uppercase">Welcome to my rails project!</h2>
            <p class="text-slate-300">This is home page</p>
        </div> 
    </figure> 
    <main class="px-10 mt-10">
        <div class="grid grid-cols-3 gap-6 items-center">
            <div>
                <h3 class="text-black font-semibold underline text-xl">Heading 1</h3>
                <p class="text-slate-600 text-sm italic">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Enim laborum iure labore nemo rerum odio blanditiis neque, 
                    fugiat dolorem obcaecati saepe impedit aut facere consectetur ex quia. 
                    Enim illum, eligendi, quod laborum odio veniam explicabo, quibusdam necessitatibus error cupiditate beatae?
                </p>
            </div>
            <div>
                <h3 class="text-black font-semibold underline text-xl">Heading 2</h3>
                <p class="text-slate-600 text-sm italic">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Enim laborum iure labore nemo rerum odio blanditiis neque, 
                    fugiat dolorem obcaecati saepe impedit aut facere consectetur ex quia. 
                    Enim illum, eligendi, quod laborum odio veniam explicabo, quibusdam necessitatibus error cupiditate beatae?
                </p>
            </div>
            <div>
                <h3 class="text-black font-semibold underline text-xl">Heading 3</h3>
                <p class="text-slate-600 text-sm italic">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Enim laborum iure labore nemo rerum odio blanditiis neque, 
                    fugiat dolorem obcaecati saepe impedit aut facere consectetur ex quia. 
                    Enim illum, eligendi, quod laborum odio veniam explicabo, quibusdam necessitatibus error cupiditate beatae?
                </p>
            </div>
        </div>
    </main>
</div>